addresses:
  kafka: 18.216.242.38
spring:
  kafka:
    consumer:
      bootstrap-servers: ${addresses.kafka}:9092
      group-id: "NOTIFICATOR"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: ${addresses.kafka}:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
