server:
  servlet:
    context-path: /notificator
addresses:
  kafka: 18.216.242.38
spring:
  kafka:
    consumer:
      bootstrap-servers: ${addresses.kafka}:9092
      group-id: "NOTIFICATOR"
      value-deserializer: br.com.smartservice.notificator.notificator.configurations.NotificatorCustomDeserializer
      max-poll-records: 1