server:
  servlet:
    context-path: /notificator
addresses:
  kafka: 10.0.10.188
spring:
  main:
    banner-mode: off
  application:
    name: notificator
  output:
    ansi:
      enabled: always
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    devtools:
      add-properties: false
  kafka:
    consumer:
      bootstrap-servers: ${addresses.kafka}:9092
      group-id: "NOTIFICATOR"
      value-deserializer: br.com.smartservice.notificator.notificator.configurations.NotificatorCustomDeserializer
      max-poll-records: 1
logging:
  level:
    web: DEBUG
    sql: DEBUG
